mutation AddProject($name: String!, $description: String!, $git: String) {
    addProject(name: $name, description: $description, git: $git) {
        id
        active
        createdAt
        description
        git
        name
        updatedAt
    }
}
