query GetTagSummaries($skip: Int, $take: Int, $order: [ProjectTagSummarySortInput!], $where: ProjectTagSummaryFilterInput, $showOrphaned: Boolean!) {
    tagSummaries(skip: $skip, take: $take, order: $order, where: $where, showOrphaned: $showOrphaned) {
        items {
            id
            name
            value
            projectsCount
        }
        pageInfo {
            hasNextPage
            hasPreviousPage
        }
        totalCount
    }
}
