query GetProjects(
    $skip: Int!
    $take: Int!
    $includeUnpublished: Boolean!
    $where: ProjectFilterInput
    $order: [ProjectSortInput!]
) {
    projects(
        skip: $skip
        take: $take
        includeUnpublished: $includeUnpublished
        where: $where,
        order: $order
    ) {
        items {
            id
            title
            body
            publishedAt
            createdAt
            updatedAt
            summary
            status
        }
        totalCount
        pageInfo { hasNextPage hasPreviousPage }
    }
}
