query GetProjects($includeUnpublished: Boolean!, $first: Int, $after: String, $order: [ProjectSortInput!], $where: ProjectFilterInput) {
    projects(
        includeUnpublished: $includeUnpublished
        first: $first
        after: $after
        order: $order
        where: $where
    ) {
        __typename
        nodes {
            __typename
            id
            title
            body
            publishedAt
            createdAt
        }
        pageInfo {
            __typename
            hasNextPage
            hasPreviousPage
            endCursor
        }
    }
}
