query GetAllProjects {
    projects {
        nodes {
            description
            git
            image {
                altText
            }
            name
        }
        errors
    }
}
