query GetProjects($skip: Int!, $take: Int!) {
    projects(skip: $skip, take: $take) {
        nodes {
            description
            id
            git
            image {
                altText
            }
            name
        }
        count
        errors
    }
}
