query GetProjects($skip: Int, $take: Int) {
    projects(skip: $skip, take: $take) {
        nodes {
            description
            git
            image {
                altText
            }
            name
        }
        errors
    }
}
