query GetProjects($skip: Int!, $take: Int!) {
    projects(skip: $skip, take: $take) {
        nodes {
            active
            description
            id
            git
            imageUrl
            name
        }
        count
        errors
    }
}
