query GetPublishedProjects($skip: Int, $take: Int, $tagValues: [String!]) {
  publishedProjects(skip: $skip, take: $take, tagValues: $tagValues) {
    items {
      ...PublicProject
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    totalCount
  }
}
