fragment PublicProject on PublicProjectDto {
  id
  title
  summary
  body
  publishedAt
  images {
    ...PublicProjectImage
  }
  links {
    ...PublicProjectLink
  }
  tags {
    id
    name
    value
  }
}
